import {catalog} from './furniture.js';
import {supportSurfaces,descendants,elevation,mountType,ceilingHeight} from './placement.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function placementFields(f,items,house){const excluded=descendants(items,f.id),parents=items.filter(p=>p.id!==f.id&&!excluded.has(p.id)&&supportSurfaces(p).length),mode=mountType(f);
 return `<details class="placement-settings" open><summary>擺放與安裝</summary><label>擺放方式<select name="mountType">${[['floor','地板（拖曳可自動放上檯面）'],['surface','物件頂面'],['wall','壁掛／手動離地']].map(([id,label])=>`<option value="${id}" ${mode===id?'selected':''}>${label}</option>`).join('')}</select></label><div class="field-row two"><label>底部離地（cm）<input name="elevation" type="number" inputmode="decimal" min="0" max="${ceilingHeight(house)*100}" step="any" value="${Number((elevation(f)*100).toFixed(3))}"></label><label>物件屬性<select name="objectKind"><option value="furniture" ${f.objectKind!=='fixture'?'selected':''}>活動家具</option><option value="fixture" ${f.objectKind==='fixture'?'selected':''}>固定設備</option></select></label></div><label>支撐物<select name="supportParentId"><option value="">未指定</option>${parents.map(p=>`<option value="${esc(p.id)}" ${p.id===f.supportParentId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><p class="inline-note">選「物件頂面」及支撐物，再套用。第一次放置會對齊有效檯面中央；外框須完整放得下。壁掛高度是物件底部距地板，不是物件本身高度。</p><label class="support-check"><input name="supportEnabled" type="checkbox" ${(f.supportEnabled??!!catalog[f.type].support)?'checked':''}>頂面可承載物品</label><p class="inline-note">自訂 GLB 請確認頂部確實平坦再啟用；系統依縮放後外框計算。</p></details>
 ${f.type==='modularWardrobe'?`<fieldset class="fixture-options"><legend>衣櫃樣式</legend><label>門片<select name="wardrobeStyle">${[['double','雙門'],['multi','多門（依寬度分片）'],['sliding','滑門（依寬度分片）']].map(([id,label])=>`<option value="${id}" ${(f.wardrobe?.style??'multi')===id?'selected':''}>${label}</option>`).join('')}</select></label><label>門板顏色<input name="doorColor" type="color" value="${f.wardrobe?.doorColor??f.color}"></label><button type="button" id="fit-ceiling">高度設為天花板下 1 cm</button><p class="inline-note">目前天花板 ${ceilingHeight(house)*100} cm；模型高度含所有門板與櫃體。</p></fieldset>`:''}
 ${f.type==='countertop'?`<label class="support-check"><input name="kitchenSink" type="checkbox" ${f.kitchen?.sink?'checked':''}>含內嵌水槽（只開放左右檯面支撐）</label>`:''}
 ${f.type==='hob'?`<label>爐口數<select name="burners"><option value="2" ${f.kitchen?.burners!==3?'selected':''}>2 口</option><option value="3" ${f.kitchen?.burners===3?'selected':''}>3 口</option></select></label>`:''}`;
}
export function readPlacement(form,f){const d=new FormData(form),mount=d.get('mountType'),value={mountType:mount,y:mount==='wall'?Number(d.get('elevation'))/100:mount==='surface'?elevation(f):0,objectKind:d.get('objectKind'),supportParentId:mount==='surface'?d.get('supportParentId')||null:null,supportEnabled:d.has('supportEnabled')};
 if(f.type==='modularWardrobe')value.wardrobe={style:d.get('wardrobeStyle'),doorColor:d.get('doorColor')};
 if(['countertop','hob'].includes(f.type))value.kitchen={sink:d.has('kitchenSink'),burners:Number(d.get('burners')??f.kitchen?.burners??2)};return value;
}
export function wirePlacement(form,house){const button=form.querySelector('#fit-ceiling');if(button)button.onclick=()=>{form.elements.height.value=Math.max(1,Math.floor(ceilingHeight(house)*100-Number(form.elements.elevation.value)-1));};}
